# Generated by Django 3.1.3 on 2020-11-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, max_length=9, verbose_name='Precio')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
