# Generated by Django 3.1.3 on 2020-11-10 01:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20201109_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(max_length=255, null=True, verbose_name='Disponiblidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='product',
            name='code_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Condición del producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Estilo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2, max_length=9, null=True, verbose_name='Precio'),
        ),
    ]
