# Generated by Django 3.1.3 on 2020-11-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_product_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
