# Generated by Django 3.1.3 on 2020-11-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20201109_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_condition',
            field=models.CharField(max_length=255, null=True, verbose_name='Condición del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(max_length=255, null=True, verbose_name='Estilo'),
        ),
    ]
