# Generated by Django 3.1.3 on 2020-11-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20201109_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=9, max_digits=19, max_length=9, null=True, verbose_name='Precio'),
        ),
    ]
