# Generated by Django 3.1.3 on 2020-11-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20201109_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='carousel/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': ' Carousel ',
                'verbose_name_plural': 'Carousel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='personal/%Y/%m/%d', verbose_name='Imagen')),
                ('name_lastname', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': ' Personal ',
                'verbose_name_plural': 'Personal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=255, null=True, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': ' Deporte ',
                'verbose_name_plural': 'Deportes',
                'ordering': ['id'],
            },
        ),
    ]
