# Generated by Django 3.1.3 on 2020-11-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_sport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
