# Generated by Django 3.1.3 on 2020-11-12 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20201111_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': ' Producto ', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Nombre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': ' Tipo de producto ',
                'verbose_name_plural': 'Tipos de producto',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='typeProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.typeproduct', verbose_name='Tipo de producto'),
        ),
    ]
