# Generated by Django 3.1.3 on 2020-11-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_auto_20201111_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
