# Generated by Django 3.1.3 on 2020-11-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_typeproduct_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
